version: "3.8"

x-common:
  &common
  env_file: ./.env
  networks:
    - mysql-network
  restart: always

services:
  database:
    image: mariadb:latest
    <<: *common
    env_file:
      - .env.database
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/my.cnf:/etc/my.cnf

  bot:
    <<: *common
    image: "drakexorn/thermostat-bot:3.0.0-SNAPSHOT"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - bot_logs:/app/logs
    depends_on:
      database:
        condition: service_healthy

volumes:
  mysql:
  bot_logs:

networks:
  mysql-network:
